name       : spirv-cross
version    : '20210115'
release    : 3
source     :
    - https://github.com/KhronosGroup/SPIRV-Cross/archive/refs/tags/2021-01-15.tar.gz : d700863b548cbc7f27a678cee305f561669a126eb2cc11d36a7023dfc462b9c4
license    : Apache-2.0
component  : programming.tools
summary    : SPIRV-Cross is a tool designed for parsing and converting SPIR-V to other shader languages
description: |
    SPIRV-Cross is a practical tool and library for performing reflection on SPIR-V and disassembling SPIR-V back to high level languages.
builddeps  :
    - glslang
    - python-nose
    - spirv-tools
setup      : |
    %patch -p1 < $pkgfiles/system-glslang-and-spirv-tools.patch
    %cmake_ninja -DSPIRV_CROSS_SHARED=ON -DPYTHON_EXECUTABLE=/usr/bin/python3
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check || :
